version: "3"
services:
    neo4j:
        image: neo4j:latest
        ports:
            - "7474:7474"
            - "7687:7687"
        environment:
            NEO4J_AUTH: "none"
        user: $UID:$GID
        volumes:
            - ./neo4j/data:/data
#            - ./neo4j/logs:/logs
        container_name: neo4j-container

    scipy-notebook:
        build:
            context: .
            dockerfile: Dockerfile
        restart: always
#        image: jupyter/scipy-notebook
        ports:
            - "8888:8888"
        environment:
            - NB_UID=$UID
            - NB_GID=$GID
        hostname: $HOSTNAME.$DNSDOMAINNAME
        user: root
        volumes:
            - ./notebooks:/home/jovyan/work:Z
            - ./data:/tmp/data:Z
        container_name: scipy-notebook-container
        links:
            - neo4j:neo4j
