version: "3"
services:

    neo4j-allquanta:
        image: neo4j:3.4.0
        ports:
            - "7474:7474"
            - "7687:7687"
        privileged: true
        environment:
            - NEO4J_dbms_security_procedures_unrestricted=apoc.*,algo.*
            - NEO4J_apoc_export_file_enabled=true
            - NEO4J_apoc_import_file_enabled=true
            - NEO4J_dbms_shell_enabled=true
            - NEO4J_AUTH=neo4j/myneo
            - NEO4J_dbms_memory_heap_max__size=400G
            - NEO4J_dbms_memory_heap_initial__size=400G
            - NEO4J_dbms_memory_pagecache_size=400G
            - NEO4J_dbms_connector_bolt_advertised__address=:7687
        user: $UID:$GID
        volumes:
            - ./neo4j/neo4j-allquanta/data:/data
            - ./neo4j/neo4j-allquanta/plugins:/plugins
            - ./neo4j/neo4j-allquanta/logs:/logs
            - ./data:/import
        container_name: neo4j-allquanta
    
#    neo4j-magtwo:
#        image: neo4j:3.4.0
#        ports:
#            - "7475:7474"
#            - "7688:7687"
#        privileged: true
#        environment:
#            - NEO4J_dbms_security_procedures_unrestricted=apoc.*,algo.*
#            - NEO4J_apoc_export_file_enabled=true
#            - NEO4J_apoc_import_file_enabled=true
#            - NEO4J_dbms_shell_enabled=true
#            - NEO4J_AUTH=neo4j/myneo
#            - NEO4J_dbms_memory_heap_max__size=5G
#            - NEO4J_dbms_memory_heap_initial__size=5G
#            - NEO4J_dbms_memory_pagecache_size=5G
#            - NEO4J_dbms_connector_bolt_advertised__address=:7688
#        user: $UID:$GID
#        volumes:
#            - ./neo4j/neo4j-magtwo/data:/data
#            - ./neo4j/neo4j-magtwo/plugins:/plugins
#            - ./neo4j/neo4j-magtwo/logs:/logs
#            - ./data:/import
#        container_name: neo4j-magtwo
#        command: "start-notebook.sh --NotebookApp.token='scaling-science'"

    scipy-notebook:
        build:
            context: .
            dockerfile: Dockerfile
        restart: always
        ports:
            - "1234:8888"
        environment:
            - NB_UID=$UID
            - NB_GID=$GID
        hostname: $HOSTNAME.$DNSDOMAINNAME
        user: root
        volumes:
            - ./notebooks:/home/jovyan/work:Z
            - ./data:/tmp/data:Z
            - ./neo4j:/tmp/neo4j:Z  
        container_name: scipy-notebook
        links:
            - neo4j-allquanta:neo4j-allquanta
#            - neo4j-magtwo:neo4j-magtwo
