version: "3"
services:
    
    neo4j:
        image: neo4j:3.5
        ports:
            - "7474:7474"
            - "7687:7687"
        privileged: true
        environment:
            - NEO4J_dbms_memory_heap_initial__size=31g
            - NEO4J_dbms_memory_heap_max__size=31g
            - NEO4J_dbms_memory_pagecache_size=76g
            - NEO4J_dbms_tx__log_rotation_retention__policy=true
            - NEO4J_dbms_tx__log_rotation_size=500M
            - NEO4J_unsupported_dbms_tx__log_fail__on__corrupted__log__files=false
            - NEO4J_dbms_checkpoint_iops_limit=-1
            - NEO4J_dbms_checkpoint_interval_time=1h
            - NEO4J_dbms_checkpoint_interval_tx=100000000
            - NEO4J_dbms_config_strict__validation=false
            - NEO4J_dbms_security_procedures_unrestricted=apoc.*,embedding.*,algo.*,regression.*
            - NEO5J_dbms_security_procedures_whitelist=apoc.*,embedding.*,algo.*,regression.*
            - NEO4J_apoc_export_file_enabled=true
            - NEO4J_apoc_import_file_enabled=true
            - NEO4J_dbms_shell_enabled=true
            - NEO4J_AUTH=neo4j/myneo
            - NEO4J_dbms_connector_bolt_advertised__address=${FQDN}:7687
            - NEO4J_dbms_connector_bolt_enabled=true
            - NEO4J_dbms_connectors_default__listen__address=0.0.0.0
            - NEO4J_dbms_connector_bolt_listen__address=:7687
            - TZ=America/New_York
        user: $UID:$GID
        ulimits:
            nofile:
                soft: 65535
                hard: 65535
        volumes:
            - ${DBBASE}/${DBNAME}/data:/data
            - ${DBBASE}/${DBNAME}/plugins:/plugins
            - ${DBBASE}/${DBNAME}/logs:/logs
            - ./data:/import
        container_name: ${DBNAME}_neo4j

    scipy-notebook:
        build:
            context: .
            dockerfile: Dockerfile
        restart: always
        ports:
            - "1234:8888"
        environment:
#            - NB_UID=$UID
#            - NB_GID=$GID
            - TZ=America/New_York
        hostname: $HOSTNAME.$DNSDOMAINNAME
        user: root  
        volumes:
            - ./notebooks:/home/jovyan/work:Z
            - ./data:/tmp/data:Z
            - ./neo4j:/tmp/neo4j:Z
        container_name: ${DBNAME}_scipy-notebook
        links:
            - neo4j:neo4j
