version: "3"
services:

    neo4j-quanta:
        image: neo4j:3.4.0
        ports:
            - "7474:7474"
            - "7687:7687"
        privileged: true
        environment:
            - NEO4J_dbms_security_procedures_unrestricted=apoc.*,algo.*
            - NEO4J_apoc_export_file_enabled=true
            - NEO4J_apoc_import_file_enabled=true
            - NEO4J_dbms_shell_enabled=true
            - NEO4J_AUTH=neo4j/myneo
            - NEO4J_dbms_memory_heap_max__size=500G
            - NEO4J_dbms_memory_heap_initial__size=500G
            - NEO4J_dbms_memory_pagecache_size=500G
            - NEO4J_dbms_connector_bolt_advertised__address=:7687
        user: $UID:$GID
        volumes:
            - ./neo4j/neo4j-quanta/data:/data
            - ./neo4j/neo4j-quanta/plugins:/plugins
            - ./neo4j/neo4j-quanta/logs:/logs
            - ./data:/import
        container_name: neo4j-quanta
    
#    neo4j-quanta-two:
#        image: neo4j:3.4.0
#        ports:
#            - "7475:7474"
#            - "7688:7687"
#        privileged: true
#        environment:
#            - NEO4J_dbms_security_procedures_unrestricted=apoc.*,algo.*
#            - NEO4J_apoc_export_file_enabled=true
#            - NEO4J_apoc_import_file_enabled=true
#            - NEO4J_dbms_shell_enabled=true
#            - NEO4J_AUTH=neo4j/myneo
#            - NEO4J_dbms_memory_heap_max__size=50G
#            - NEO4J_dbms_memory_heap_initial__size=50G
#            - NEO4J_dbms_memory_pagecache_size=50G
#            - NEO4J_dbms_connector_bolt_advertised__address=:7687
#        user: $UID:$GID
#        volumes:
#            - ./neo4j/neo4j-quanta-two/data:/data
#            - ./neo4j/neo4j-quanta-two/plugins:/plugins
#            - ./neo4j/neo4j-quanta-two/logs:/logs
#            - ./data:/import
#        container_name: neo4j-quanta-two

    scipy-notebook:
        build:
            context: .
            dockerfile: Dockerfile
        restart: always
        ports:
            - "8888:8888"
        environment:
            - NB_UID=$UID
            - NB_GID=$GID
        hostname: $HOSTNAME.$DNSDOMAINNAME
        user: root
        volumes:
            - ./notebooks:/home/jovyan/work:Z
            - ./data:/tmp/data:Z
            - ./neo4j:/tmp/neo4j:Z  
        container_name: scipy-notebook-container
        links:
            - neo4j-quanta:neo4j-quanta
#            - neo4j-quanta-two:neo4j-quanta-two
