version: "3"
services:
   # neo4j:
   #     image: neo4j:latest
   #     ports:
   #         - "7474:7474"
   #         - "7687:7687"
   #     # environment:
   #     #     NEO4J_AUTH: username:password
   #     container_name: neo4j-container

    scipy-notebook:
        image: jupyter/scipy-notebook
        ports:
            - "8888:8888"
        environment:
            - NB_UID=$UID
            - NB_GID=$GID
        user: root
        volumes:
            - ./notebooks:/home/jovyan/work:z
            - ./data:/tmp/data:Z
        container_name:   scipy-notebook-container
        # links:
        #     neo4j
