#!/bin/bash

# First argument should be the directory with training data, full of year directories that were each generated by asymproj_edge_dnn

if [ -z "$1" ]; then # no argumment passed, run for default directory
  DBASE=/mnt/raid/data/features/top84/embeddings/optimized
  DIR=$DBASE/training_data/*
  echo "To run for the non-default directory, pass an argument with the directory that contains the edgelists for all years"
  for d in $DIR; do
    #echo Making train test splits for $d && \
    YEAR=${d: -4} && \
    echo "Training for $d"
    python3 train_test_split.py $d && \
    echo "Created train test split" && \
    python3 -m graph_attention_learning --dataset_dir=$d --output_dir=$DBASE/result/$YEAR
  done
  echo "Finished writing emveddungs to $DBASE/training_data"
else
  DBASE=$1
  DIR=$DBASE/training_data/*
  for d in $DIR; do
    echo "Training for $d" && \
    YEAR=${d: -4} && \
    python3 train_test_split.py $d && \
    echo "Created train test split" && \
    python3 -W ignore -m graph_attention_learning --dataset_dir=$d --output_dir=$DBASE/result/$YEAR
  done
  echo "Finished writing all train test splits to $DBASE/training_data"
fi
