version: "3"
services:

    scipy-notebook:
        build:
            context: .
            dockerfile: Dockerfile
        restart: always
        ports:
            - "1234:8888"
        environment:
            - NB_UID=$UID
            - NB_GID=$GID
        hostname: $HOSTNAME.$DNSDOMAINNAME
        user: root
        volumes:
            - ./:/home/jovyan/work:Z
        container_name: joe-notebook
        command: "start-notebook.sh --NotebookApp.token='01f969db8a2720c17e5809d2c5aa20b183c117af1cdede54'"
